services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: paydb
    ports:
      - "5433:5432"   # было "5433:5433"
    volumes:
      - ./_data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d paydb"]
      interval: 5s
      timeout: 3s
      retries: 10